web:
  build: .
  working_dir: /home/app
  ports:
    - "3000:3000"
    - "5858:5858"
  command: npm run build
  environment:
    NODE_ENV: development
  links:
    - mongo
mongo:
  image: mongo:latest
  command: mongod --smallfiles --quiet --logpath=/dev/null
  ports:
   - "27017:27017"
